name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

              - name: Start backend
        run: |
          npm run start &
          sleep 5

      - name: Validate endpoints
        run: |
          curl -f http://localhost:3000/api/status
          curl -f http://localhost:3000/api/users

                - name: Wait for backend
        run: npx wait-on http://localhost:3000/api/status